namespace OOP_saudio_sim_csharp.Presepi
{
   /// <summary>
   ///  Plug-in is an additional, visual or sound, feature of listener.
   ///  This interface represents the basic operation that every
   ///  plug-in implemented must have.
   /// </summary>
    public interface IPlugin
    {
        /// <summary>
        /// Active the audio changes generated by this plug-in. 
        ///Keep the configuration if it has been previously disabled.
        /// </summary>
        void Enable();
        
        /// <summary>
        /// Disable the audio changes and restore the default value. 
        /// </summary>
        void Disable();
        
        bool IsEnabled { get; }
        
        string GetClassName();
    }
}